dist:
  module: github.com/go-follow/open-telemetry-test/cmd/otelcustom
  name: otelcustom
  description: custom otel-collector
  output_path: ./otel-custom
  otelcol_version: 0.89.0
  version: 0.0.6
#  go: /usr/local/go/bin/go

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.89.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.89.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.89.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.89.0
#  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.89.0
  - gomod: github.com/go-follow/open-telemetry-test/receiver/myprometheusreceiver v0.0.6

replaces:
  - github.com/go-follow/open-telemetry-test/receiver/myprometheusreceiver => ../../receiver/myprometheusreceiver
